declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_BACKEND_SERVER_BASE_URL: string;
    NEXT_PUBLIC_FRONTEND_SERVER_BASE_URL: string;
    NEXT_PUBLIC_AMPLITUDE_API_KEY: string;
    NEXT_PUBLIC_IMAGE_S3_DOMAIN: string;
    NEXT_PUBLIC_IMAGE_CLOUDFRONT_DOMAIN: string;
    NEXT_PUBLIC_CDN_DOMAIN: string;
    VIEW_DATA_FILE_PATH: string;
    VIEW_DATA_FLUSH_THRESHOLD: string;
  }
}
