name: Sync Issue Info to PR

on:
  pull_request:
    types: [opened]
    branches: [develop]

jobs:
  sync-issue-meta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync Issue Metadata to PR
        uses: jinhokim98/project-flow-sync-issue-meta-to-pr@v1
        with:
          github_token: ${{ secrets.CONFIG_SUBMODULE_TOKEN }}
          project_owner: "Crew-Wiki"
          project_number: 13
          target_column: "In Review"

      - name: Set PR Assignees and Reviewers
        uses: jinhokim98/project-flow-set-pr-assignees-and-reviewers@v1
        with:
          github_token: ${{ secrets.CONFIG_SUBMODULE_TOKEN }}
          reviewers: "jinhokim98,Todari,ShinjungOh,chosim-dvlpr,eunwoo-levi"
